# Task 1 

Write a program that allows you to enter 4 numbers
and stores them in a file called “Numbers”
3
45
83
21
Have a go at ‘w’ ‘r’ ‘a’

In [1]:
my_file=open("Numbers.txt", "w")
f_number=input ("Enter First Number ")
s_number= input ("Enter Second Number ")
t_number= input ("Enter Third Number ")
l_number= input ("Enter Last Number ")

my_file.write(f_number)
my_file.write("\n")
my_file.write(s_number)
my_file.write("\n")
my_file.write(t_number)
my_file.write("\n")
my_file.write(l_number)

my_file.close()



Appending the file



In [8]:
my_file=open("Numbers.txt", "a")
f=input ("Enter the content you want to add to the file 'Numbers' ")

my_file.write(f)
my_file.write("\n")

1

Reading the file and printing the content of the file

In [6]:
my_file=open("Numbers.txt", "r")

print (my_file.read())

56
67
80
12021
2021



# Task 2

Write a program to ask a student for their percentage mark and convert this to a grade.
The conversion will be done in a function called mark_grade

In [4]:
print ("Conversion from percentage mark to Grade", "\n")
name= input ("Enter your name ")
print ("Hello", name)

def mark_grade(marks):
    if marks >=90 and marks < 101:
        print ("Your Grade is A+")
    elif marks >=80 and marks < 90:
        print ("Your Grade is A")
    elif marks >=75 and marks < 80:
        print ("Your Grade is B+")
    elif marks >69 and marks < 75:
        print ("Your Grade is B")
    elif marks > 64 and marks < 70:
        print ("Your Grade is C+")
    elif marks >54 and marks < 65:
        print ("Your Grade is C")
    elif marks >49 and marks < 60:
        print ("Your Grade is D")
    elif marks >39 and marks < 50:
        print ("Your Grade is E")
    elif marks >=0 and marks < 40:
        print ("Your Grade is F")
    else:
        print ("Error")

marks=int(input ("Enter percentage marks between 0 and 100: "))
mark_grade(marks)

target_grade= input("What's your target grade ")
print ("Target grade ",target_grade, "Percentage Marks ",marks,"%")
if target_grade == 'A+' or target_grade == 'a+':
    print ("Congratulations on your achievement, Target Grade is more than Exam Grade")
elif target_grade == 'A' or target_grade == 'a':
        print ("Congratulations on your achievement, Target Grade is more than Exam Grade")
elif target_grade == 'B+' or target_grade=='b+':
    print ("Congratulations! you have achieved the Exam Grade")
else:
    print ("Unfortunately you haven't been successful on this occassion")



Conversion from percentage mark to Grade 

Hello Bilal
Your Grade is A+
Target grade  A Percentage Marks  91 %
Congratulations on your achievement, Target Grade is more than Exam Grade


# Home Learning Project 

1. Creating a 1D array of numbers from 0 to 9

In [4]:
import numpy as np 
arr= np.arange(10)
print (arr)

[0 1 2 3 4 5 6 7 8 9]


2. Creating a 33×3 NumPy array of all Boolean value Trues

In [24]:
import numpy as np
arr= np.random.randint(1,5, size=(33,3))
newarr= arr.astype(bool)
print (newarr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


3. Extract all odd numbers from array of 1 10

In [5]:
import numpy as np 
arr= np.arange(1,10,2)
print (arr)

[1 3 5 7 9]


4. Replace all odd numbers in an array of 1 10 with the value -1

In [25]:
import numpy as np 
arr= np.arange(0,11)
print (arr)
for i in range (1,len(arr),2):
  arr[i]= '-1'
print (arr)


[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0 -1  2 -1  4 -1  6 -1  8 -1 10]


5. Convert a 1D array to a 2D array with 2 rows

In [43]:
import numpy as np
arr= np.array([1,2,3,4,6,7,8,9])
newArray= arr.reshape(-1,2)
print (newArray)

[[1 2]
 [3 4]
 [6 7]
 [8 9]]


6. Create two arrays a and b, stack these two arrays vertically use the np.dot and
np.sum to calculate totals.

In [95]:
import numpy as np 
a= np.array([[1,2], [10,20]])
print (a)
b= np.array ([[5,6], [10,20]])
print (b)
print ("Stacking two arrays vertically \n")
c= np.vstack ((a,b))
print (c)
matrix_multiply= np.dot(a,b)
print ("Matrix multiplication \n")
print (matrix_multiply)
arr_sum=np.sum(matrix_multiply)
print ("Sum \n ", (arr_sum) )


[[ 1  2]
 [10 20]]
[[ 5  6]
 [10 20]]
Stacking two arrays vertically 

[[ 1  2]
 [10 20]
 [ 5  6]
 [10 20]]
Matrix multiplication 

[[ 25  46]
 [250 460]]
Sum 
  781


# Extension:

Create the following pattern without hardcoding. Use only NumPy functions
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]

In [114]:
import numpy as np
a= np.array ([[1,2,3]])
b = np.repeat (a,3)
print (b)
c= np.tile (a,3)
print (c)
#print (np.repeat (a, 3))
d= np.concatenate((b,c), axis=None)
print (d)

[1 1 1 2 2 2 3 3 3]
[[1 2 3 1 2 3 1 2 3]]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) remove all repeating items present in array b.

In [120]:
a = ([1,2,3,4,5,])
b= ([4,5,6,7,8,9])
c= np.concatenate ((a,b), axis=None)
print (c)
new_arr = list( dict.fromkeys(c) )
print(new_arr)

[1 2 3 4 5 4 5 6 7 8 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


Get all items between 3 and 7 from a and b and sum them together.

In [134]:
a = ([1,2,3,4,5,])
b= ([4,5,6,7,8,9])
c= np.concatenate ((a,b), axis=None)
print (c)
sum=0 
for i in c: 
    if i>=3 and i<=7:
        sum+=i
print(sum)


[1 2 3 4 5 4 5 6 7 8 9]
34
